-- REFERÊNCIA CATALOGADA DO GOOGLE DRIVE
-- Pasta lógica: consultas_sql_topo
-- Arquivo: E110_REG_0000.sql
-- URL de origem: https://drive.google.com/file/d/1a5xXpD9_g8XHYG8EXy8UwiN6M9aJ1R2P/view?usp=drivesdk
-- Situação nesta atualização: catalogado a partir do Google Drive.
-- Observação: o conector abriu a estrutura da pasta e permitiu o inventário dos arquivos,
-- mas a extração integral em lote de todos os SQLs não foi concluída nesta mesma passada.
-- Este arquivo funciona como marcador auditável para extração incremental posterior.
