-- REFERÊNCIA CATALOGADA DO GOOGLE DRIVE
-- Pasta lógica: consultas_sql_topo
-- Arquivo: Dados_Cálculo_Ressarcimento_ST_C196_Fronteira_após_2022.sql
-- URL de origem: https://drive.google.com/file/d/1EWvw2K7kOV5CZdUJsoMlXnHEtfcQ1ESm/view?usp=drivesdk
-- Situação nesta atualização: catalogado a partir do Google Drive.
-- Observação: o conector abriu a estrutura da pasta e permitiu o inventário dos arquivos,
-- mas a extração integral em lote de todos os SQLs não foi concluída nesta mesma passada.
-- Este arquivo funciona como marcador auditável para extração incremental posterior.
