/*
CONSULTA EXTRAÍDA DE XML DE PAINEL
ORIGEM_XML: dossie_contribuinte.xml
CAMINHO_NO_XML: Dossiê Contribuinte NIF - 4.3.7 > NFs - Entr X Saida (VAF)
ESTILO: Table
HABILITADA: true
BINDS:
 - CO_CNPJ_CPF | prompt=CO_CNPJ_CPF | default=NULL_VALUE
OBSERVACAO:
 - SQL extraído do XML sem alteração funcional.
 - Tags HTML, formatação de apresentação e scripts de SQL*Plus foram preservados quando existentes.
*/
SELECT
							:CO_CNPJ_CPF CO_CNPJ_CPF,
							ANO,
							LPAD(TRIM(TO_CHAR(ENTRADA, '999G999G999G990D00')), LENGTH(MAX(ENTRADA)OVER()) + 7) 							ENTRADA,
							LPAD(TRIM(TO_CHAR(SAIDA, '999G999G999G990D00')),LENGTH(MAX(SAIDA)OVER()) + 7) 								SAIDA,
							LPAD(TRIM(TO_CHAR(SAIDA-ENTRADA, '999G999G999G990D00')),LENGTH(MAX(SAIDA-ENTRADA)OVER()) + 7)				DIFERENCA,
							CASE
								WHEN NVL(ENTRADA,0) = 0 THEN 'N/D'
								WHEN NVL(SAIDA, 0) / NVL(ENTRADA, 0) < 1
									THEN '<HTML><B STYLE="COLOR:#D7463A">'|| NVL(ROUND(((NVL(SAIDA,0)-NVL(ENTRADA,0))/NVL(ENTRADA,0))*100,2),2)||'%'
								ELSE'<HTML><B STYLE="COLOR:#3A51D7">'||NVL(ROUND(((NVL(SAIDA,0)-NVL(ENTRADA,0))/NVL(ENTRADA,0))*100,2),2)||'%'
							END          																								AGREG
							FROM
							(SELECT
									EXTRACT(YEAR FROM DA_REFERENCIA) ANO,
									SUM( CASE
											WHEN T.CO_EMITENTE = :CO_CNPJ_CPF     AND T.CO_TP_NF = 1 THEN (T.PROD_VPROD + PROD_VFRETE + PROD_VSEG + PROD_VOUTRO - PROD_VDESC) --CNPJ NO CO_EMITENTE DE EMISSÃO PRÓPRIA
											WHEN T.CO_DESTINATARIO = :CO_CNPJ_CPF AND T.CO_TP_NF = 0 THEN (T.PROD_VPROD + PROD_VFRETE + PROD_VSEG + PROD_VOUTRO - PROD_VDESC) --CNPJ NO CO_DESTINATÁRIO DE EMISSÃO DE TERCEIRO
											ELSE 0 END )                                                                                SAIDA,
									SUM( CASE
											WHEN T.CO_DESTINATARIO = :CO_CNPJ_CPF AND T.CO_TP_NF = 1 THEN (T.PROD_VPROD + PROD_VFRETE + PROD_VSEG + PROD_VOUTRO - PROD_VDESC) --CNPJ NO CO_DESTINATPARIO DE EMISSÃO PRÓPRIA
											WHEN T.CO_EMITENTE = :CO_CNPJ_CPF     AND T.CO_TP_NF = 0 THEN (T.PROD_VPROD + PROD_VFRETE + PROD_VSEG + PROD_VOUTRO - PROD_VDESC) --CNPJ NO CO_EMITENTE DE EMISSÃO DE TERCEIRO
											ELSE 0 END )                                                                                ENTRADA
								FROM
										 BI.FATO_NFE_NFCE_SUMARIZADA T
									INNER JOIN BI.DM_CFOP C ON T.CO_CFOP = C.CO_CFOP
								WHERE
									( T.CO_EMITENTE = :CO_CNPJ_CPF OR T.CO_DESTINATARIO = :CO_CNPJ_CPF )
									AND C.IN_VAF = 'X'
								GROUP BY GROUPING SETS((:CO_CNPJ_CPF),(EXTRACT(YEAR FROM DA_REFERENCIA)))
								ORDER BY ANO DESC)
