-- CPF_NF_entrada_saida_VAF.sql
-- Extraído de dossie_contribuinte.xml - NFs Entrada X Saída (VAF)
-- Parâmetro: :CO_CNPJ_CPF

SELECT
    :CO_CNPJ_CPF CO_CNPJ_CPF,
    ANO,
    ENTRADA,
    SAIDA,
    (SAIDA - ENTRADA) DIFERENCA,
    CASE
        WHEN NVL(ENTRADA,0) = 0 THEN 'N/D'
        WHEN NVL(SAIDA, 0) / NVL(ENTRADA, 0) < 1
            THEN ROUND(((NVL(SAIDA,0)-NVL(ENTRADA,0))/NVL(ENTRADA,0))*100,2)||'%'
        ELSE ROUND(((NVL(SAIDA,0)-NVL(ENTRADA,0))/NVL(ENTRADA,0))*100,2)||'%'
    END AGREGACAO_PERCENTUAL
FROM
(SELECT
    EXTRACT(YEAR FROM DA_REFERENCIA) ANO,
    SUM(CASE
        WHEN T.CO_EMITENTE = :CO_CNPJ_CPF AND T.CO_TP_NF = 1 THEN (T.PROD_VPROD + PROD_VFRETE + PROD_VSEG + PROD_VOUTRO - PROD_VDESC)
        WHEN T.CO_DESTINATARIO = :CO_CNPJ_CPF AND T.CO_TP_NF = 0 THEN (T.PROD_VPROD + PROD_VFRETE + PROD_VSEG + PROD_VOUTRO - PROD_VDESC)
        ELSE 0
    END) SAIDA,
    SUM(CASE
        WHEN T.CO_DESTINATARIO = :CO_CNPJ_CPF AND T.CO_TP_NF = 1 THEN (T.PROD_VPROD + PROD_VFRETE + PROD_VSEG + PROD_VOUTRO - PROD_VDESC)
        WHEN T.CO_EMITENTE = :CO_CNPJ_CPF AND T.CO_TP_NF = 0 THEN (T.PROD_VPROD + PROD_VFRETE + PROD_VSEG + PROD_VOUTRO - PROD_VDESC)
        ELSE 0
    END) ENTRADA
FROM
    BI.FATO_NFE_NFCE_SUMARIZADA T
    INNER JOIN BI.DM_CFOP C ON T.CO_CFOP = C.CO_CFOP
WHERE
    (T.CO_EMITENTE = :CO_CNPJ_CPF OR T.CO_DESTINATARIO = :CO_CNPJ_CPF)
    AND C.IN_VAF = 'X'
GROUP BY EXTRACT(YEAR FROM DA_REFERENCIA)
ORDER BY ANO DESC)
