-- CPF_NF_entrada_detalhe.sql
-- Extraído de dossie_contribuinte.xml - Notas de Entrada detalhadas
-- Parâmetro: :CO_CNPJ_CPF

SELECT 
    D.CHAVE_ACESSO,
    D.PROD_NITEM,
    D.NNF,
    D.DHEMI DATA_EMISSAO,
    CASE 
        WHEN D.CO_TP_NF = 0 THEN 'ENTRADA'
        WHEN D.CO_TP_NF = 1 THEN 'SAÍDA'
    END TIPO_NF,
    D.CO_EMITENTE,
    D.XNOME_EMIT NOME_EMITENTE,
    D.CO_UF_EMIT UF_EMITENTE,
    D.CO_DESTINATARIO,
    D.XNOME_DEST NOME_DESTINATARIO,
    D.CO_UF_DEST UF_DESTINATARIO,
    D.PROD_XPROD DESCRICAO_PRODUTO,
    D.PROD_NCM NCM,
    D.CO_CFOP CFOP,
    D.PROD_QCOM QUANTIDADE,
    D.PROD_VPROD VALOR_PRODUTO,
    D.PROD_VFRETE VALOR_FRETE,
    D.PROD_VDESC VALOR_DESCONTO,
    D.ICMS_VBC BASE_CALCULO_ICMS,
    D.ICMS_VICMS VALOR_ICMS,
    D.ICMS_VICMSST VALOR_ICMS_ST,
    CASE 
        WHEN D.INFPROT_CSTAT = 0 THEN 'CANCELAMENTO PELO EMITENTE'
        WHEN D.INFPROT_CSTAT = 100 THEN 'AUTORIZADA'
        WHEN D.INFPROT_CSTAT = 150 THEN 'AUTORIZAÇÃO FORA DE PRAZO'
        WHEN D.INFPROT_CSTAT = 301 THEN 'DENEGADO: SITUAÇÃO DO EMITENTE'
        WHEN D.INFPROT_CSTAT = 302 THEN 'DENEGADO: SITUAÇÃO DO DESTINATÁRIO'
        WHEN D.INFPROT_CSTAT = 303 THEN 'DENEGADO: DESTINATÁRIO NÃO HABILITADO NA UF'
    END STATUS_NF
FROM bi.fato_nfe_detalhe d
WHERE (
    (d.co_destinatario = :CO_CNPJ_CPF AND d.co_tp_nf = 1)
    OR (d.co_emitente = :CO_CNPJ_CPF AND d.co_tp_nf = 0)
)
AND d.infprot_cstat IN ('100','150')
ORDER BY d.dhemi DESC, d.chave_acesso, d.prod_nitem
