-- CPF_empresa_CFOP.sql
-- Análise de CFOP das notas fiscais recebidas pela empresa (compras)
-- Parâmetro: :CO_CNPJ_CPF (14 dígitos - CNPJ)

SELECT
    d.CO_DESTINATARIO AS CNPJ_DESTINATARIO,
    TO_CHAR(d.DHEMI, 'YYYY/MM') AS MES_REFERENCIA,
    d.CO_CFOP AS CFOP,
    cfop.DESCRICAO_CFOP AS DESCRICAO_CFOP,

    COUNT(DISTINCT d.CHAVE_ACESSO) AS QTD_NFS,
    COUNT(*) AS QTD_ITENS,

    SUM(d.PROD_VPROD) AS VALOR_PRODUTOS,
    SUM(NVL(d.PROD_VFRETE,0)) AS VALOR_FRETE,
    SUM(NVL(d.PROD_VSEG,0)) AS VALOR_SEGURO,
    SUM(NVL(d.PROD_VOUTRO,0)) AS VALOR_OUTROS,
    SUM(NVL(d.PROD_VDESC,0)) AS VALOR_DESCONTO,
    SUM(d.PROD_VPROD + NVL(d.PROD_VFRETE,0) + NVL(d.PROD_VSEG,0) + NVL(d.PROD_VOUTRO,0) - NVL(d.PROD_VDESC,0)) AS VALOR_TOTAL,

    COUNT(DISTINCT d.CO_EMITENTE) AS QTD_FORNECEDORES

FROM bi.fato_nfe_detalhe d
LEFT JOIN bi.dm_cfop cfop ON d.CO_CFOP = cfop.CO_CFOP
WHERE d.CO_DESTINATARIO = :CO_CNPJ_CPF
  AND d.CO_CFOP IS NOT NULL
  AND d.INFPROT_CSTAT IN (100, 150)
GROUP BY
    d.CO_DESTINATARIO,
    TO_CHAR(d.DHEMI, 'YYYY/MM'),
    d.CO_CFOP,
    cfop.DESCRICAO_CFOP
ORDER BY
    MES_REFERENCIA DESC,
    VALOR_TOTAL DESC
