-- REFERÊNCIA CATALOGADA DO GOOGLE DRIVE
-- Pasta lógica: consultas_sql_subpasta_CPF
-- Arquivo: CPF_NF_entrada_quantidades.sql
-- URL de origem: https://drive.google.com/file/d/1g07DaBgI2adA0hJIFf_rBhYj49E3ASxI/view?usp=drivesdk
-- Situação nesta atualização: catalogado a partir do Google Drive.
-- Observação: o conector abriu a estrutura da pasta e permitiu o inventário dos arquivos,
-- mas a extração integral em lote de todos os SQLs não foi concluída nesta mesma passada.
-- Este arquivo funciona como marcador auditável para extração incremental posterior.
