-- Tabela CEST-NCM - 1º nível
SELECT IT_NU_CEST, IT_NU_NCM, IT_CO_SEFIN, SP_NU_CEST_NCM
FROM SITAFE.SITAFE_CEST_NCM
WHERE IT_IN_STATUS <> 'C'
ORDER BY IT_NU_CEST, IT_NU_NCM;

-- Tabela CEST - 2º nível
SELECT  A.IT_NU_CEST AS CEST,
        A.IT_CO_SEFIN AS "CO-SEFIN"
FROM    SITAFE.SITAFE_CEST A
WHERE   IT_IN_STATUS <> 'C'
ORDER BY  A.IT_NU_CEST;

-- Tabela NCM - 3º nível
SELECT  A.TUK,
        A.IT_NU_NCM AS NCM,
        B.IT_NU_CLASSIFICACAO AS "CO-SEFIN",
        A.IT_CO_PRODUTO_ST AS "REGUL.-ST",
        A.IT_CO_PRODUTO_ISENTO AS "REGUL.-ISENTO",
        A.IT_IN_INSUMO AS "INSUMO RURAL",
        A.IT_CO_PRODUTO_INSUMO AS "COD.INSUMO",
        A.IT_IN_PREVALECE_ABCFARMA AS "PREVALECE S/ABCFARMA?",
        A.IT_NO_NCM AS DESCRIÇÃO
FROM SITAFE.SITAFE_NCM A
LEFT OUTER JOIN SITAFE.SITAFE_NCM_GR_CLASSIF_PRODUTO B ON A.TUK = B.TUK
WHERE   IT_IN_STATUS_NCM <> 'C'
ORDER BY A.IT_NU_NCM