SELECT
IT_CO_SEF,
TO_DATE(IT_DA_INICIO, 'YYYYMMDD') IT_DA_INICIO,
CASE
    WHEN TRIM(IT_DA_FINAL) IS NULL THEN SYSDATE ELSE TO_DATE
END IT_DA_FINAL,
IT_PC_IMPOSTO,
IT_IN_R,
IT_PC_RVA,
IT_IN_RVA_AJUSTADO,
IT_IN_CONVENIO,
IT_IN_ISENTO_NCS,
IT_IN_REDUCAO,
IT_IN_REDUCAO_CREDITO,
IT_IN_IPI,
IT_IN_COMBUSTIVEL,
IT_IN_REDUCAO_CREDITO,
IT_UF_OR, IT_UF_AM, IT_UF_AP, IT_UF_BA, IT_UF_CE,
IT_IN_IMPORT

FROM sitafe.sitafe_produto_sefin_aux a
INNER JOIN sitafe.sitafe_ncm_mercadoria b ON b.it_co_sefin = A.it_co_sefin
WHERE b.it_nu_NCM ='10064000'
