-- REFERÊNCIA CATALOGADA DO GOOGLE DRIVE
-- Pasta lógica: consultas_sql_subpasta_CPF
-- Arquivo: CPF_empresa_reg_pgto.sql
-- URL de origem: https://drive.google.com/file/d/1mUTRSITwD1d96E014X6K8r-y_QKG8aqW/view?usp=drivesdk
-- Situação nesta atualização: catalogado a partir do Google Drive.
-- Observação: o conector abriu a estrutura da pasta e permitiu o inventário dos arquivos,
-- mas a extração integral em lote de todos os SQLs não foi concluída nesta mesma passada.
-- Este arquivo funciona como marcador auditável para extração incremental posterior.
